void Test()
{
  // Cause an exception
  CheckFunc();
}
